apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: break-psp
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: break-psp
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
- kind: ServiceAccount
  name: default
  namespace: demo
- kind: ServiceAccount
  name: default
  namespace: sock-shop
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: break-psp
