apiVersion: security-profiles-operator.x-k8s.io/v1beta1
kind: SeccompProfile
metadata:
  namespace: gadget
  name: profile
spec:
  defaultAction: SCMP_ACT_ERRNO
  syscalls:
    - action: SCMP_ACT_ALLOW
      names:
        - accept4
        - access
        - arch_prctl
        - bind
        - bpf
        - brk
        - capget
        - capset
        - chdir
        - clock_gettime
        - clone
        - close
        - connect
        - dup
        - dup2
        - dup3
        - epoll_create1
        - epoll_ctl
        - epoll_pwait
        - epoll_wait
        - eventfd2
        - execve
        - exit_group
        - faccessat
        - faccessat2
        - fanotify_init
        - fanotify_mark
        - fcntl
        - fstat
        - fstatfs
        - futex
        - getcwd
        - getdents64
        - getegid
        - geteuid
        - getgid
        - getpeername
        - getpgrp
        - getpid
        - getppid
        - getrandom
        - getrlimit
        - getsockname
        - getsockopt
        - gettid
        - getuid
        - ioctl
        - keyctl
        - listen
        - lseek
        - lstat
        - madvise
        - mkdir
        - mkdirat
        - mmap
        - mount
        - mprotect
        - munmap
        - name_to_handle_at
        - nanosleep
        - newfstatat
        - openat
        - perf_event_open
        - pidfd_open
        - pipe
        - pipe2
        - ppoll
        - prctl
        - pread64
        - prlimit64
        - read
        - readlinkat
        - rt_sigaction
        - rt_sigprocmask
        - rt_sigreturn
        - sched_getaffinity
        - sched_yield
        - seccomp
        - sendmsg
        - set_robust_list
        - set_tid_address
        - setgid
        - setgroups
        - setns
        - setsid
        - setsockopt
        - setuid
        - sigaltstack
        - socket
        - stat
        - statfs
        - sysinfo
        - tgkill
        - umask
        - uname
        - unlinkat
        - unshare
        - wait4
        - write
