name: Compile bpftool with patches
on:
  #push:
  schedule:
    - cron: '0 2 1 * *' # Monthly builds at 02:00

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Publish to Registry
      id: publish-registry
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: docker.io/kinvolk/bpftool
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: gadget-ds
        dockerfile: bpftool.Dockerfile
        snapshot: true
        cache: ${{ github.event_name != 'schedule' }}

