name: Compile inspektor-gadget
on:
  push:
  schedule:
    - cron: '0 2 * * *' # Night builds at 02:00

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Build gadget container and publish to Registry
      id: publish-registry
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: docker.io/kinvolk/gadget
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: gadget-ds
        dockerfile: gadget.Dockerfile
        snapshot: true
        cache: ${{ github.event_name != 'schedule' }}

    - name: Build inspektor-gadget
      run: |
        TAG=$(git describe --tags --always)
        CHANGES=$(git status --porcelain)
        if [ "$CHANGES" = "" ] ; then
          VERSION="$TAG"
        else
          VERSION="$TAG"-dirty
        fi

        LDFLAGS1="-X github.com/kinvolk/inspektor-gadget/cmd/inspektor-gadget/cmd.version=${VERSION}"
        LDFLAGS2="-X github.com/kinvolk/inspektor-gadget/cmd/inspektor-gadget/cmd.gadgetimage=docker.io/kinvolk/gadget:${{steps.publish-registry.outputs.snapshot-tag}}"
        LDFLAGS3="-extldflags '-static'"

        GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build \
            -ldflags "$LDFLAGS1 $LDFLAGS2 $LDFLAGS3" \
            -o inspektor-gadget \
            github.com/kinvolk/inspektor-gadget/cmd/inspektor-gadget

    - name: Upload inspektor-gadget artifact
      uses: actions/upload-artifact@v1
      with:
        name: inspektor-gadget
        path: inspektor-gadget

